# Coords of btns the bot tries to press.
[lobby]
select_btn = [150, 950]
trophy_observer = [20, 10, 650, 200]
[template_matching]
powerpoint = [1000, 5, 80, 80]
brawler_menu_task = [1450, 0, 80, 80]
close_popup = [1740, 140, 140, 100]
lobby_menu = [1790, 20, 75, 65]
brawl_pass_house = [1750, 0, 169, 100]
go_back_arrow = [0, 0, 175, 110]
star_drop = [790, 350, 350, 350]

